#!/bin/bash
#This script is used to tell the details of elements when atomic number of that element is given as input

if [ $# -ne 0 ]
then
	echo -e "\e[1;31m !!Synatx Error!!\e[0m \n see the \e[1;34m Syntax: ./ptable.sh\e[0m"
	exit 1
fi

echo -e "\e[1;30m ----\e[0m""												      ""\e[1;35m ----\e[0m"
echo -e "\e[1;30m|1   |\e[0m""												      ""\e[1;35m|2   |\e[0m"
echo -e "\e[1;30m|H   |\e[0m""												      ""\e[1;35m|He  |\e[0m"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""							      ""\e[1;31m   ----\e[0m""\e[1;34m  ----  ----  ----  ----\e[0m""\e[1;35m  ----\e[0m"
echo -e "\e[1;30m|3   |\e[0m""\e[1;36m|4   |\e[0m""								""\e[1;31m|5   |\e[0m""\e[1;34m|6   |\e[0m""\e[1;34m|7   ||8   ||9   |\e[0m""\e[1;35m|10  |\e[0m"
echo -e "\e[1;30m|Li  |\e[0m""\e[1;36m|Be  |\e[0m""								""\e[1;31m|B   |\e[0m""\e[1;34m|C   ||N   ||O   ||F   |\e[0m""\e[1;35m|Ne  |\e[0m"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""							      ""\e[1;31m   ----\e[0m""\e[1;32m  ----\e[0m""\e[1;34m  ----  ----  ----\e[0m""\e[1;35m  ----\e[0m" 
echo -e "\e[1;30m|11  |\e[0m""\e[1;36m|12  |\e[0m""								""\e[1;31m|13  |\e[0m""\e[1;32m|14  |\e[0m""\e[1;34m|15  ||16  ||17  |\e[0m""\e[1;35m|18  |\e[0m"
echo -e "\e[1;30m|Na  |\e[0m""\e[1;36m|Mg  |\e[0m""								""\e[1;31m|Al  |\e[0m""\e[1;32m|Si  |\e[0m""\e[1;34m|P   ||S   ||Cl  |\e[0m""\e[1;35m|Ar  |\e[0m"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""\e[1;33m  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----\e[0m""\e[1;31m  ----\e[0m""\e[1;32m  ----  ----\e[0m""\e[1;34m  ----  ----\e[0m""\e[1;35m  ----\e[0m"
echo -e "\e[1;30m|19  |\e[0m""\e[1;36m|20  |\e[0m""\e[1;33m|21  ||22  ||23  ||24  ||25  ||26  ||27  ||28  ||29  ||30  |\e[0m""\e[1;31m|31  |\e[0m""\e[1;32m|32  ||33  |\e[0m""\e[1;34m|34  ||35  |\e[0m""\e[1;35m|36  |\e[0m"
echo -e "\e[1;30m|K   |\e[0m""\e[1;36m|Ca  |\e[0m""\e[1;33m|Sc  ||Ti  ||V   ||Cr  ||Mn  ||Fe  ||Ni  ||Co  ||Cu  ||Zn  |\e[0m""\e[1;31m|Ga  |\e[0m""\e[1;32m|Ge  ||As  |\e[0m""\e[1;34m|Se  ||Br  |\e[0m""\e[1;35m|Kr  |\e[0m"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""\e[1;33m  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----\e[0m""\e[1;31m  ----\e[0m""\e[1;32m  ----  ----\e[0m""\e[1;34m  ----  ----\e[0m""\e[1;35m  ----\e[0m"
echo -e "\e[1;30m|37  |\e[0m""\e[1;36m|38  |\e[0m""\e[1;33m|39  ||40  ||41  ||42  ||43  ||44  ||45  ||46  ||47  ||48  |\e[0m""\e[1;31m|49  ||50  |\e[0m""\e[1;32m|51  ||52  |\e[0m""\e[1;34m|53  |\e[0m""\e[1;35m|54  |\e[0m"
echo -e "\e[1;30m|Rb  |\e[0m""\e[1;36m|Sr  |\e[0m""\e[1;33m|Y   ||Zr  ||Nb  ||Mo  ||Tc  ||Ru  ||Rh  ||Pd  ||Ag  ||Cd  |\e[0m""\e[1;31m|In  ||Sn  |\e[0m""\e[1;32m|Sb  ||Te  |\e[0m""\e[1;34m|I   |\e[0m""\e[1;35m|Xe  |\e[0m"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""\e[1;33m  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----\e[0m""\e[1;31m  ----  ----\e[0m""\e[1;32m  ----  ----\e[0m""\e[1;34m  ----\e[0m""\e[1;35m  ----\e[0m"
echo -e "\e[1;30m|55  |\e[0m""\e[1;36m|56  |\e[0m""\e[1;33m      |72  ||73  ||74  ||75  ||76  ||77  ||78  ||79  ||80  |\e[0m""\e[1;31m|81  ||82  ||83  ||84  |\e[0m""\e[1;32m|85  |\e[0m""\e[1;35m|86  |\e[0m"
echo -e "\e[1;30m|Cs  |\e[0m""\e[1;36m|Ba  |\e[0m""\e[1;33m      |Hf  ||Ta  ||W   ||Re  ||Os  ||Ir  ||Pt  ||Au  ||Hg  |\e[0m""\e[1;31m|Tl  ||Pb  ||Bi  ||Po  |\e[0m""\e[1;32m|At  |\e[0m""\e[1;35m|Rn  |\e[0m"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""\e[1;33m        ----  ----  ----  ----  ----  ----  ----  ----  ----\e[0m""\e[1;31m  ----  ----  ----  ----\e[0m""\e[1;32m  ----\e[0m""\e[1;35m  ----\e[0m"
echo -e "\e[1;30m|87  |\e[0m""\e[1;36m|88  |\e[0m""\e[1;33m      |104 ||105 ||106 ||107 ||108 |\e[0m""|109 ||110 ||111 |""\e[1;33m|112 |\e[0m""|113 |""\e[1;31m|114 |\e[0m""|115 ||116 ||117 ||118 |"
echo -e "\e[1;30m|Fr  |\e[0m""\e[1;36m|Ra  |\e[0m""\e[1;33m      |Rf  ||Db  ||Sg  ||Bh  ||Hs  |\e[0m""|Mt  ||Ds  ||Rg  |""\e[1;33m|Cn  |\e[0m""|Nh  |""\e[1;31m|Fl  |\e[0m""|Mc  ||Lv  ||Ts  ||Og  |"
echo -e "\e[1;30m ----\e[0m""\e[1;36m  ----\e[0m""\e[1;33m	   ----  ----  ----  ----  ----\e[0m""  ----  ----  ---- ""\e[1;33m ----\e[0m""  ---- ""\e[1;31m ----\e[0m""  ----  ----  ----  ----"
echo -e ""
echo -e ""
echo -e "		  \033[38;5;208m ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----\033[m"
echo -e "		  \033[38;5;208m|57  ||58  ||59  ||60  ||61  ||62  ||63  ||64  ||65  ||66  ||67  ||68  ||69  ||70  ||71  |\033[m"
echo -e "		  \033[38;5;208m|La  ||Ce  ||Pr  ||Nd  ||Pm  ||Sm  ||Eu  ||Gd  ||Tb  ||Dy  ||Ho  ||Er  ||Tm  ||Yb  ||Lu  |\033[m"
echo -e "		  \033[38;5;208m ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----\033[m"
echo -e "		  \033[38;5;215m|89  ||90  ||91  ||92  ||93  ||94  ||95  ||96  ||97  ||98  ||99  ||100 ||101 ||102 ||103 |\033[m"
echo -e "		  \033[38;5;215m|Ac  ||Th  ||Pa  ||U   ||Np  ||Pu  ||Am  ||Cm  ||Bk  ||Cf  ||Es  ||Fm  ||Md  ||No  ||Lr  |\033[m"
echo -e "		  \033[38;5;215m ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ----\033[m"

read -p "Select an atomic number: " a ; clear

case $a
in 
	1)echo -e "\e[0;31m Name: Hydrogen \n Atomic Weight: 1.0079 \n Atomic number: 1 \n Latin name: No latin name \n State: Gas \n Class: Non-metal \n Block name: S-block element \n Group number:1 or IA \n Period number: 1 \n Symbol: \n $(figlet -c H)\e[0m";;
	2)echo -e "\e[0;32m Name: Helium \n Atomic Weight: 4.00 \n Atomic number: 2 \n Latin name: no latin name \n State: Gas \n Class: Nobel gas \n Block name: P-block element \n Group number: 18 or VIIIB \n Period number: 1 \n Symbol: \n $(figlet -c He)\e[0m";;
	3)echo -e "\e[0;33m Name: Lithium \n Atomic Weight: 6.94 \n Atomic number: 3 \n Latin name: no latin name \n State: Solid \n Class: Alkali metals \n Block name: S-block element \n Group number: 1 or IA \n Period number: 2 \n Symbol: \n $(figlet -c Li)\e[0m";;
	4)echo -e "\e[0;34m Name: Beryllium \n Atomic Weight: 9.01 \n Atomic number: 4 \n Latin name: no latin name \n State: Solid \n Class: Alkaline earth metals \n Block name: S-block element \n Group number: 2 or IIA \n Period number: 2 \n Symbol: \n $(figlet -c Be)\e[0m";;
	5)echo -e "\e[0;35m Name: Boron \n Atomic Weight: 10.81 \n Atomic number: 5 \n Latin name: no latin name \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 13 or IIIA \n Period number: 2 \n Symbol: \n $(figlet -c B)\e[0m";;
	6)echo -e "\e[0;36m Name: Carbon \n Atomic Weight: 12.01 \n Atomic number: C \n Latin name: no latin name \n State: Solid \n Class: Non-metal \n Block name: P-block element \n Group number: 14 or IVA \n Period number: 2 \n Symbol: \n $(figlet -c C)\e[0m";;
	7)echo -e "\e[1;30m Name: Nitrogen \n Atomic Weight: 14.0067 \n Atomic number: 7 \n Latin name: no latin name \n State: Gas \n Class: Non-metal \n Block name: P-block element \n Group number: 15 or VA \n Period number: 2 \n Symbol: \n $(figlet -c N)\e[0m";;
	8)echo -e "\e[1;31m Name: Oxygen \n Atomic Weight: 16.00 \n Atomic number: 8 \n Latin name: no latin name \n State: Gas \n Class: Non-metal \n Block name: P-block element \n Group number: 16 or VIA \n Period number: 2 \n Symbol: \n $(figlet -c O)\e[0m";;
	9)echo -e "\e[1;32m Name: Fluorine \n Atomic Weight: 19.00 \n Atomic number: 9 \n Latin name: no latin name \n State: Gas \n Class: Non-metal \n Block name: P-block element \n Group number: 17 or VIIA \n Period number: 2 \n Symbol: \n $(figlet -c F)\e[0m";;
	10)echo -e "\e[1;36m Name: Neon \n Atomic Weight: 20.18 \n Atomic number: 10 \n Latin name: no latin name \n State: Gas \n Class: Nobel gas \n Block name: P-block element \n Group number: 18 or VIIIA \n Period number: 2 \n Symbol: \n $(figlet -c Ne)\e[0m";;
	11)echo -e "\e[0;31m Name: Sodium \n Atomic Weight: 22.99 \n Atomic number: 11 \n Latin name: Natrium \n State: Solid \n Class: Alkali metals \n Block name: S-block element \n Group number: 1 or IA \n Period number: 3 \n Symbol: \n $(figlet -c Na)\e[0m";;
	12)echo -e "\e[0;32m Name: Magnesium \n Atomic Weight: 24.31 \n Atomic number: 12 \n Latin name: no latin name \n State: Solid \n Class: Alkaline earth metals \n Block name: S-block element \n Group number: 2 or IIA \n Period number: 3 \n Symbol: \n $(figlet -c Mg)\e[0m";;
	13)echo -e "\e[0;33m Name: Aluminium \n Atomic Weight: 26.98 \n Atomic number: 13 \n Latin name: no latin name \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 13 or IIIA \n Period number: 3 \n Symbol: \n $(figlet -c Al)\e[0m";;
	14)echo -e "\e[0;34m Name: Silicon \n Atomic Weight: 28.08 \n Atomic number: 14 \n Latin name: no latin name \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 14 or IVA \n Period number: 3 \n Symbol: \n $(figlet -c Si)\e[0m";;
	15)echo -e "\e[0;35m Name: Phosphorus \n Atomic Weight: 30.97 \n Atomic number: 15 \n Latin name: no latin name \n State: Solid \n Class: Non-metal \n Block name: P-block element \n Group number: 15 or VA \n Period number: 3 \n Symbol: \n $(figlet -c P)\e[0m";;
	16)echo -e "\e[0;36m Name: Sulphur \n Atomic Weight: 32.06 \n Atomic number: 16 \n Latin name: no latin name \n State: Solid \n Class: Non-metal \n Block name: P-block element \n Group number: 16 or VIA \n Period number: 3 \n Symbol: \n $(figlet -c S)\e[0m";;
	17)echo -e "\e[1;30m Name: Chlorine \n Atomic Weight: 35.45 \n Atomic number: 17 \n Latin name: no latin name \n State: Gas \n Class: Non-metal \n Block name: P-block element \n Group number: 17 or VIIA \n Period number: 3 \n Symbol: \n $(figlet -c Cl)\e[0m";;
	18)echo -e "\e[1;31m Name: Argon \n Atomic Weight: 39.95 \n Atomic number: 18 \n Latin name: no latin name \n State: Gas \n Class: Nobel gas \n Block name: P-block element \n Group number: 18 or VIIIA \n Period number: 3 \n Symbol: \n $(figlet -c Ar)\e[0m";;
	19)echo -e "\e[1;32m Name: Potassium \n Atomic Weight: 39.10 \n Atomic number: 19 \n Latin name: kalium \n State: Solid \n Class: Alkali metals \n Block name: S-block element \n Group number: 1 or IA \n Period number: 4 \n Symbol: \n $(figlet -c K)\e[0m";;
	20)echo -e "\e[1;36m Name: Calcium \n Atomic Weight: 40.08 \n Atomic number: 20 \n Latin name: no latin name \n State: Solid \n Class: Alkaline earth metals \n Block name: S-block element \n Group number: 2 or IIA \n Period number: 4 \n Symbol: \n $(figlet -c Ca)\e[0m";;
	21)echo -e "\e[0;31m Name: Scandium \n Atomic Weight: 44.96 \n Atomic number: 21 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 3 or IIIB \n Period number: 4 \n Symbol: \n $(figlet -c Sc)\e[0m";;
	22)echo -e "\e[0;32m Name: Titanium \n Atomic Weight: 47.88 \n Atomic number: 22 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 4 or IVB \n Period number: 4 \n Symbol: \n $(figlet -c Ti)\e[0m";;
	23)echo -e "\e[0;33m Name: Vanadium \n Atomic Weight: 50.94 \n Atomic number: 23 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 5 or VB \n Period number: 4 \n Symbol: \n $(figlet -c V)\e[0m";;
	24)echo -e "\e[0;34m Name: Chromium \n Atomic Weight: 52.00 \n Atomic number: 24 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 6 or VIB \n Period number: 4 \n Symbol: \n $(figlet -c Cr)\e[0m";;
	25)echo -e "\e[0;35m Name: Manganese \n Atomic Weight: 54.94 \n Atomic number: 25 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 7 or VIIB \n Period number: 4 \n Symbol: \n $(figlet -c Mn)\e[0m";;
	26)echo -e "\e[0;36m Name: Iron \n Atomic Weight: 55.85 \n Atomic number: 26 \n Latin name: Ferrum \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 8 or VIIIB \n Period number: 4 \n Symbol: \n $(figlet -c Fe)\e[0m";;
	27)echo -e "\e[1;30m Name: Cobalt \n Atomic Weight: 58.93 \n Atomic number: 27 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 9 or VIIIB \n Period number: 4 \n Symbol: \n $(figlet -c Co)\e[0m";;
	28)echo -e "\e[1;31m Name: Nickel \n Atomic Weight: 58.71 \n Atomic number: 28 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 10 or VIIIB \n Period number: 4 \n Symbol: \n $(figlet -c Ni)\e[0m";;
	29)echo -e "\e[1;32m Name: Copper \n Atomic Weight: 63.54 \n Atomic number: 29 \n Latin name: cuprum \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 11 or IB \n Period number: 4 \n Symbol: \n $(figlet -c Cu)\e[0m";;
	30)echo -e "\e[1;36m Name: Zinc \n Atomic Weight: 65.37 \n Atomic number: 30 \n Latin name: no latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 12 or IIB \n Period number: 4 \n Symbol: \n $(figlet -c Zn)\e[0m";;
	31)echo -e "\e[0;31m Name: Gallium \n Atomic Weight: 69.72 \n Atomic number: 31 \n Latin name: No latin name \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 13 or IIIA \n Period number: 4 \n Symbol: \n $(figlet -c Ga)\e[0m";;
	32)echo -e "\e[0;32m Name: Germanium \n Atomic Weight: 72.63 \n Atomic number: 32 \n Latin name: No latin name \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 14 or IVA \n Period number: 4 \n Symbol: \n $(figlet -c Ge)\e[0m";;
	33)echo -e "\e[0;33m Name: Arsenic \n Atomic Weight: 74.92 \n Atomic number: 33 \n Latin name: No latin name \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 15 or VA \n Period number: 4 \n Symbol: \n $(figlet -c As)\e[0m";;
	34)echo -e "\e[0;34m Name: P-block element Selenium \n Atomic Weight: 78.97 \n Atomic number: 34 \n Latin name: No latin name \n State: Solid \n Class: Non-metal \n Block name: \n Group number: 16 or VIA \n Period number: 4 \n Symbol: \n $(figlet -c Se)\e[0m";;
	35)echo -e "\e[0;35m Name: Bromine \n Atomic Weight: 79.90 \n Atomic number: 35 \n Latin name: No latin name \n State: Liquid \n Class: Non-metal \n Block name: P-block element \n Group number: 17 or VIIA \n Period number: 4 \n Symbol: \n $(figlet -c Br)\e[0m";;
	36)echo -e "\e[0;36m Name: Krypton \n Atomic Weight: 83.79 \n Atomic number: 36 \n Latin name: No latin name \n State: Gas \n Class: Nobel gas \n Block name: P-block element \n Group number: 18 or VIIIA \n Period number: 4 \n Symbol: \n $(figlet -c Kr)\e[0m";;
	37)echo -e "\e[1;30m Name: Rubidium \n Atomic Weight: 85.46 \n Atomic number: 37 \n Latin name: No latin name \n State: Solid \n Class: Alkali metals \n Block name: S-block element \n Group number: 1 or IA \n Period number: 5 \n Symbol: \n $(figlet -c Ru)\e[0m";;
	38)echo -e "\e[1;31m Name: Strontium \n Atomic Weight: 87.62 \n Atomic number: 38 \n Latin name: No latin name \n State: Solid \n Class: Alkaline earth metals \n Block name: S-block element \n Group number: 2 or IIA \n Period number: 5 \n Symbol: \n $(figlet -c Sr)\e[0m";;
	39)echo -e "\e[1;32m Name: Yttrium \n Atomic Weight: 88.90 \n Atomic number: 39 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 3 or IIIB \n Period number: 5 \n Symbol: \n $(figlet -c Y)\e[0m";;
	40)echo -e "\e[1;36m Name: Zirconium \n Atomic Weight: 91.22 \n Atomic number: 40 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 4 or IVB \n Period number: 5 \n Symbol: \n $(figlet -c Zr)\e[0m";;
	41)echo -e "\e[0;31m Name: Niobium \n Atomic Weight: 92.90 \n Atomic number: 41 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 5 or VB \n Period number: 5 \n Symbol: \n $(figlet -c Nb)\e[0m";;
	42)echo -e "\e[0;32m Name: Molybdenum \n Atomic Weight: 95.95 \n Atomic number: 42 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 6 or VIB \n Period number: 5 \n Symbol: \n $(figlet -c Mo)\e[0m";;
	43)echo -e "\e[0;33m Name: Technetium* \n Atomic Weight: (98) \n Atomic number: 43 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 7 or VIIB \n Period number: 5 \n Half-life: 2,11,000y \n Symbol: \n $(figlet -c Tc) \n ----------------------------------------- \n *means its a radioactive element. \e[0m";;
	44)echo -e "\e[0;34m Name: Ruthenium \n Atomic Weight: 101.07 \n Atomic number: 44 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 8 or VIIIB \n Period number: 5 \n Symbol: \n $(figlet -c Ru)\e[0m";;	
	45)echo -e "\e[0;35m Name: Rhodium \n Atomic Weight: 102.91 \n Atomic number: 45 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 9 or VIIIB \n Period number: 5 \n Symbol: \n $(figlet -c Rh)\e[0m";;
	46)echo -e "\e[0;36m Name: Palladium \n Atomic Weight: 106.42 \n Atomic number: 46 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 10 or VIIIB \n Period number: 5 \n Symbol: \n $(figlet -c Pd)\e[0m";;
	47)echo -e "\e[1;30m Name: Silver \n Atomic Weight: 107.87 \n Atomic number: 47 \n Latin name: Argentum \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 11 or IB \n Period number: 5 \n Symbol: \n $(figlet -c Ag)\e[0m";;
	48)echo -e "\e[1;31m Name: Cadmium \n Atomic Weight: 112.41 \n Atomic number: 48 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 12 or IIB \n Period number: 5 \n Symbol: \n $(figlet -c Cd)\e[0m";;
	49)echo -e "\e[1;32m Name: Indium \n Atomic Weight: 114.82 \n Atomic number: 49 \n Latin name: No latin name \n State: Solid  \n Class: Post-transition metal \n Block name: P-block element \n Group number: 13 or IIIA \n Period number: 5 \n Symbol: \n $(figlet -c In)\e[0m";;
	50)echo -e "\e[1;36m Name: Tin \n Atomic Weight: 118.71 \n Atomic number: 50 \n Latin name: Stannum \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 14 or IVA \n Period number: 5 \n Symbol: \n $(figlet -c Sn)\e[0m";;
	51)echo -e "\e[0;31m Name: Antimony \n Atomic Weight: 121.76 \n Atomic number: 51 \n Latin name: Stibium \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 15 or VA \n Period number: 5 \n Symbol: \n $(figlet -c Sb)\e[0m";;
	52)echo -e "\e[0;32m Name: Tellurium \n Atomic Weight: 127.60 \n Atomic number: 52 \n Latin name: No latin name \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 16 or VIA \n Period number: 5 \n Symbol: \n $(figlet -c Te)\e[0m";;
	53)echo -e "\e[0;33m Name: Iodine \n Atomic Weight: 126.90 \n Atomic number: 53 \n Latin name: No latin name \n State: Solid \n Class: Non-metal \n Block name: P-block element \n Group number: 17 or VIIA \n Period number: 5 \n Symbol: \n $(figlet -c I)\e[0m";;
	54)echo -e "\e[0;34m Name: Xenon \n Atomic Weight: 131.29 \n Atomic number: 54 \n Latin name: No latin name \n State: Solid \n State: Gas \n Class: Nobel gas \n Block name: P-block element \n Group number: 18 or VIIIA \n Period number: 5 \n Symbol: \n $(figlet -c Xe)\e[0m";;
	55)echo -e "\e[0;35m Name: Caesium \n Atomic Weight: 132.91 \n Atomic number: 55 \n Latin name: No latin name \n State: Solid \n Class: Alkali metals \n Block name: S-block element \n Group number: 1 or IA \n Period number: 6 \n Symbol: \n $(figlet -c Cs)\e[0m";;
	56)echo -e "\e[0;36m Name: Barium \n Atomic Weight: 137.33 \n Atomic number: 56 \n Latin name: No latin name \n State: Solid \n Class: Alkaline earth metals \n Block name: S-block element \n Group number: 2 or IIA \n Period number: 6 \n Symbol: \n $(figlet -c Ba)\e[0m";;
	57)echo -e "\e[1;30m Name: Lanthanum \n Atomic Weight: 138.91 \n Atomic number: 57 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c La)\e[0m";;
	58)echo -e "\e[1;31m Name: Cerium \n Atomic Weight: 140.12 \n Atomic number: 58 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Ce)\e[0m";;
	59)echo -e "\e[1;32m Name: Praseodymium \n Atomic Weight: 140.91 \n Atomic number: 59 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Pr)\e[0m";;
	60)echo -e "\e[1;36m Name: Neodymium \n Atomic Weight: 144.24 \n Atomic number: 60 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Nd)\e[0m";;
	61)echo -e "\e[0;31m Name: Promethium \n Atomic Weight: (145) \n Atomic number: 61 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Pm)\e[0m";;
	62)echo -e "\e[0;32m Name: Samarium \n Atomic Weight: 150.36 \n Atomic number: 62 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Sm)\e[0m";;
	63)echo -e "\e[0;33m Name: Europium \n Atomic Weight: 151.96 \n Atomic number: 63 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Eu)\e[0m";;
	64)echo -e "\e[0;34m Name: Gadolinium \n Atomic Weight: 157.25 \n Atomic number: 64 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Gd)\e[0m";;
	65)echo -e "\e[0;35m Name: Terbium \n Atomic Weight: 158.93 \n Atomic number: 65 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Tb)\e[0m";;
	66)echo -e "\e[0;36m Name: Dysproium \n Atomic Weight: 162.50 \n Atomic number: 66 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Dy)\e[0m";;
	67)echo -e "\e[1;30m Name: Holmium \n Atomic Weight: 164.93 \n Atomic number: 67 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Ho)\e[0m";;
	68)echo -e "\e[1;31m Name: Erbium \n Atomic Weight: 167.26 \n Atomic number: 68 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Er)\e[0m";;
	69)echo -e "\e[1;32m Name: Thulium \n Atomic Weight: 168.93 \n Atomic number: 69 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Tm)\e[0m";;
	70)echo -e "\e[1;36m Name: Ytterbium \n Atomic Weight: 173.05 \n Atomic number: 70 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Yb)\e[0m";;
	71)echo -e "\e[0;31m Name: Lutetium \n Atomic Weight: 174.97 \n Atomic number: 71 \n Latin name: No latin name \n State: Solid \n Class: Lanthanoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 6 \n Symbol: \n $(figlet -c Lu)\e[0m";;
	72)echo -e "\e[0;32m Name: Hafnium \n Atomic Weight: 178.49 \n Atomic number: 72 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 4 or IVB \n Period number: 6 \n Symbol: \n $(figlet -c Hf)\e[0m";;
	73)echo -e "\e[0;33m Name: Tantalum \n Atomic Weight: 180.95 \n Atomic number: 73 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 5 or VB \n Period number: 6 \n Symbol: \n $(figlet -c Ta)\e[0m";;
	74)echo -e "\e[0;34m Name: Tungsten \n Atomic Weight: 183.84 \n Atomic number: 74 \n Latin name: Wolfram \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 6 or VIB \n Period number: 6 \n Symbol: \n $(figlet -c W)\e[0m";;
	75)echo -e "\e[0;35m Name: Rhenium \n Atomic Weight: 186.21 \n Atomic number: 75 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 7 or VIIB \n Period number: 6 \n Symbol: \n $(figlet -c Re)\e[0m";;
	76)echo -e "\e[0;36m Name: Osmium \n Atomic Weight: 190.23 \n Atomic number: 76 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 8 or VIIIB \n Period number: 6 \n Symbol: \n $(figlet -c Os)\e[0m";;
	77)echo -e "\e[1;30m Name: Iridium \n Atomic Weight: 192.22 \n Atomic number: 77 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 9 or VIIIB \n Period number: 6 \n Symbol: \n $(figlet -c Ir)\e[0m";;
	78)echo -e "\e[1;31m Name: Platinum \n Atomic Weight: 195.08 \n Atomic number: 78 \n Latin name: No latin name \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 10 or VIIIB \n Period number: 6 \n Symbol: \n $(figlet -c Pt)\e[0m";;
	79)echo -e "\e[1;32m Name: Gold \n Atomic Weight: 196.97 \n Atomic number: 79 \n Latin name: Aurum \n State: Solid \n Class: Transition metal \n Block name: D-block element \n Group number: 11 or IB \n Period number: 6 \n Symbol: \n $(figlet -c Au)\e[0m";;
	80)echo -e "\e[1;36m Name: Mercury \n Atomic Weight: 200.59 \n Atomic number: 80 \n Latin name: No latin name \n State: Solid \n State: Liquid \n Class: Transition metal \n Block name: D-block element \n Group number: 12 or IIB \n Period number: 6 \n Symbol: \n $(figlet -c Hg)\e[0m";;
	81)echo -e "\e[0;31m Name: Thallium \n Atomic Weight: 204.38 \n Atomic number: 81 \n Latin name: No latin name \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 13 or IIIA \n Period number: 6 \n Symbol: \n $(figlet -c Tl)\e[0m";;
	82)echo -e "\e[0;33m Name: Lead \n Atomic Weight: 207.2 \n Atomic number: 82 \n Latin name: Plumbum \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 14 or IVA \n Period number: 6 \n Symbol: \n $(figlet -c Pb)\e[0m";;
	83)echo -e "\e[0;34m Name: Bismuth \n Atomic Weight: 208.98 \n Atomic number: 83 \n Latin name: No latin name \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 15 or VA \n Period number: 6 \n Symbol: \n $(figlet -c Bi)\e[0m";;
	84)echo -e "\e[0;35m Name: Polonium* \n Atomic Weight: (209) \n Atomic number: 84 \n Latin name: No latin name \n State: Solid \n Class: Post-transition metal \n Block name: P-block element \n Group number: 16 or VIA \n Period number: 6 \n Half-life: 125y \n Symbol: \n $(figlet -c Po) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	85)echo -e "\e[0;36m Name: Astatine* \n Atomic Weight: (210) \n Atomic number: 85 \n Latin name: No latin name \n State: Solid \n Class: Metalliod \n Block name: P-block element \n Group number: 17 or VIIA \n Period number: 6 \n Half-life: 8.1h \n Symbol: \n $(figlet -c At) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	86)echo -e "\e[1;30m Name: Radon* \n Atomic Weight: (222) \n Atomic number: 86 \n Latin name: No latin name \n State: Solid \n State: Gas \n Class: Nobel gas \n Block name: P-block element \n Group number: 18 or VIIIA \n Period number: 6 \n Half-life: 3.82d \n Symbol: \n $(figlet -c Rn) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	87)echo -e "\e[1;31m Name: Francium* \n Atomic Weight: (223) \n Atomic number: 87 \n Latin name: No latin name \n State: Solid \n Class: Alkali metal \n Block name: S-block element \n Group number: 1 or IA \n Period number: 7 \n Half-life: 4.8min \n Symbol: \n $(figlet -c Fr) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	88)echo -e "\e[0;35m Name: Radium* \n Atomic Weight: (226) \n Atomic number: 88 \n Latin name: No latin name \n State: Solid \n Class: Alkaline earth metal \n Block name: S-block element \n Group number: 2 or IIA \n Period number: 7 \n Half-life: 1600y \n Symbol: \n $(figlet -c Ra) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	89)echo -e "\e[1;32m Name: Actinium* \n Atomic Weight: (227) \n Atomic number: 89 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 21.7y \n Symbol: \n $(figlet -c Ac) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	90)echo -e "\e[1;36m Name: Thorium \n Atomic Weight: 232.04 \n Atomic number: 90 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Symbol: \n $(figlet -c Th)\e[0m";;
	91)echo -e "\e[0;31m Name: Protactinium* \n Atomic Weight: 231.04 \n Atomic number: 91 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 1.17min \n Symbol: \n $(figlet -c Pa) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	92)echo -e "\e[0;32m Name: Uranium \n Atomic Weight: 238.03 \n Atomic number: 92 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Symbol: \n $(figlet -c U)\e[0m";;
	93)echo -e "\e[0;33m Name: Neptunium* \n Atomic Weight: (237) \n Atomic number: 93 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 2.35d \n Symbol: \n $(figlet -c Np) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	94)echo -e "\e[0;34m Name: Plutonium* \n Atomic Weight: (244) \n Atomic number: 94 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 2.1d \n Symbol: \n $(figlet -c Pu) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	95)echo -e "\e[0;35m Name: Americium* \n Atomic Weight: (243) \n Atomic number: 95 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 7,370y \n Symbol: \n $(figlet -c Am) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	96)echo -e "\e[0;36m Name: Curium* \n Atomic Weight: (247) \n Atomic number: 96 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life:15.6 million years \n Symbol: \n $(figlet -c Cm) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	97)echo -e "\e[1;30m Name: Berkelium* \n Atomic Weight: (247) \n Atomic number: 97 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 1,380y \n Symbol: \n $(figlet -c Bk) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	98)echo -e "\e[1;31m Name: Caliornium* \n Atomic Weight: (251) \n Atomic number: 98 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 898y \n Symbol: \n $(figlet -c Cf) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	99)echo -e "\e[1;32m Name: Einsteinium* \n Atomic Weight: (252) \n Atomic number: 99 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 20.5d \n Symbol: \n $(figlet -c Es) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	100)echo -e "\e[1;36m Name: Fermium* \n Atomic Weight: (257) \n Atomic number: 100 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 1d \n Symbol: \n $(figlet -c Fm) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	101)echo -e "\e[0;31m Name: Mendelevium* \n Atomic Weight: (258) \n Atomic number: 101 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 51.5d \n Symbol: \n $(figlet -c Md) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	102)echo -e "\e[0;32m Name: Nobelium* \n Atomic Weight: (259) \n Atomic number: 102 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 15s \n Symbol: \n $(figlet -c No) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	103)echo -e "\e[0;33m Name: Lawrencium* \n Atomic Weight: (266) \n Atomic number: 103 \n Latin name: No latin name \n State: Solid \n Class: Actinoid \n Block name: F-block element \n Group number: 3 or IIIB \n Period number: 7 \n Half-life: 39.26d \n Symbol: \n $(figlet -c Lr) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	104)echo -e "\e[0;34m Name: Rutherfordium* \n Atomic Weight: (267) \n Atomic number: 104 \n Latin name: No latin name \n State: Unknown \n Class: Transition metal \n Block name: D-block element \n Group number: 4 or IVB \n Period number: 7 \n Half-life: 1.3h \n Symbol: \n $(figlet -c Rf) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	105)echo -e "\e[0;35m Name: Dubnium* \n Atomic Weight: (268) \n Atomic number: 105 \n Latin name: No latin name \n State: Unknown \n Class: Transition metal \n Block name: D-block element \n Group number: 5 or VB \n Period number: 7 \n Half-life: 30h \n Symbol: \n $(figlet -c Db) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	106)echo -e "\e[0;36m Name: Seaborgium* \n Atomic Weight: (269) \n Atomic number: 106 \n Latin name: No latin name \n State: Unknown \n Class: Transition metal \n Block name: D-block element \n Group number: 6 or VIB \n Period number: 7 \n Half-life: 2.4min \n Symbol: \n $(figlet -c Sg) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	107)echo -e "\e[1;30m Name: Bohrium* \n Atomic Weight: (270) \n Atomic number: 107 \n Latin name: No latin name \n State: Unknown \n Class: Transition metal \n Block name: D-block element \n Group number: 7 or VIIB \n Period number: 7 \n Half-life: 61s \n Symbol: \n $(figlet -c Bh) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	108)echo -e "\e[1;31m Name: Hassium* \n Atomic Weight: (277) \n Atomic number: 108 \n Latin name: No latin name \n State: Unknown \n Class: Transition metal \n Block name: D-block element \n Group number: 8 or VIIIB \n Period number: 7 \n Half-life: 30s \n Symbol: \n $(figlet -c Hs) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	109)echo -e "\e[1;32m Name: Meitnerium* \n Atomic Weight: (278) \n Atomic number: 109 \n Latin name: No latin name \n State: Unknown \n Block name: D-block element \n Group number: 9 or VIIIB \n Period number: 7 \n Half-life: 67s \n Symbol: \n $(figlet -c Mt) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	110)echo -e "\e[1;36m Name: Darmstadtium* \n Atomic Weight: (281) \n Atomic number: 110 \n Latin name: No latin name \n State: Unknown \n Block name: D-block element \n Group number: 10 or VIIIB \n Period number: 7 \n Half-life: 10s \n Symbol: \n $(figlet -c Ds) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	111)echo -e "\e[0;31m Name: Roentgenium* \n Atomic Weight: (282) \n Atomic number: 111 \n Latin name: No latin name \n State: Unknown \n Block name: D-block element \n Group number: 11 or IB \n Period number: 7 \n Half-life: 26s \n Symbol: \n $(figlet -c Rg) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	112)echo -e "\e[0;32m Name: Copernicium* \n Atomic Weight: (285) \n Atomic number: 112 \n Latin name: No latin name \n State: Unknown \n Class: Transition metal \n Block name: D-block element \n Group number: 12 or IIB \n Period number: 7 \n Half-life: 29s \n Symbol: \n $(figlet -c Cn) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	113)echo -e "\e[0;33m Name: Nihonium* \n Atomic Weight: (286) \n Atomic number: 113 \n Latin name: No latin name \n State: Unknown \n Block name: P-block element \n Group number: 13 or IIIA \n Period number: 7 \n Half-life: 20s \n Symbol: \n $(figlet -c Nh) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	114)echo -e "\e[0;34m Name: Flerovium* \n Atomic Weight: (289) \n Atomic number: 114 \n Latin name: No latin name \n State: Unknown \n Class: Post-transition metal \n Block name: P-block element \n Group number: 14 or IVA \n Period number: 7 \n Half-life: 2.6s \n Symbol: \n $(figlet -c Fl) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	115)echo -e "\e[0;35m Name: Moscovium* \n Atomic Weight: (290) \n Atomic number: 115 \n Latin name: No latin name \n State: Unknown \n Block name: P-block element \n Group number: 15 or VA \n Period number: 7 \n Half-life: 0.8s \n Symbol: \n $(figlet -c Mc) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	116)echo -e "\e[0;36m Name: Livermorium* \n Atomic Weight: (293) \n Atomic number: 116 \n Latin name: No latin name \n State: Unknown \n Block name: P-block element \n Group number: 16 or VIA \n Period number: 7 \n Half-life: 61millisec \n Symbol: \n $(figlet -c Lv) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	117)echo -e "\e[1;30m Name: Tennessine* \n Atomic Weight: (294) \n Atomic number: 117 \n Latin name: No latin name \n State: Unknown \n Block name: P-block element \n Group number: 17 or VIIA \n Period number: 7 \n Half-life: 80millisec \n Symbol: \n $(figlet -c Ts) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	118)echo -e "\e[1;31m Name: Oganesson* \n Atomic Weight: (294) \n Atomic number: 118 \n Latin name: No latin name \n State: Unknown \n Block name: P-block element \n Group number: 18 or VIIIA \n Period number: 7 \n Half-life: 0.89millisec \n Symbol: \n $(figlet -c Og) \n ----------------------------------------- \n *means its a radioactive element.\e[0m";;
	*)echo -e "\e[0;31m :: Unknown Element ::" "\e[0;34m yet to be discovered\e[0m"
esac
